### ISSUE TITLE
Configurable metric threshold values

### ISSUE THREAD

**Issue by fkromer** [git-afsantos/haros_plugins#6]
It would be great if the threshold values for rules like the [max_cyclomatic_complexity of the lizard plugin](https://github.com/git-afsantos/haros_plugins/blob/advanced/lizard_plugin/plugin.yaml#L30) could be configured via parameters (instead of beeing hard coded as part of separate rules). If you already have a concept in mind for that let me know... I can help out to implement it.

**Comment by git-afsantos** [comment]
In that case, the rule is hardcoded because it is part of some well-known quality standards, [recommended by ROS](http://wiki.ros.org/code_quality#Function_based). But I agree that allowing users to define their own thresholds would be a good idea.

Actually, I am going through a big refactoring of data structures that hopefully will expose more information to users and allow to some degree of customization. In the meantime, or even as a permanent solution, I had thought of adding some `preferences` file to HAROS, or something of that sort, where users could fine tune some configurations, as well as passing parameters to plugins.

Example:

```yaml
metrics_thresholds:
    cyclomatic_complexity:    # id of the metric, see "definitions.yaml" in haros
        my_warning_threshold: # name for your custom threshold
            max: 12
        my_severe_threshold:
            max: 20
```

**Comment by fkromer** [comment]
> In that case, the rule is hardcoded because it is part of some well-known quality standards, recommended by ROS. But I agree that allowing users to define their own thresholds would be a good idea.

I know. But many developers prefer to gradually change analysis configurations from loose to strict settings over time instead of getting notified about all kind of things right in the beginning which makes it harder for them to focus on the most important metrics first. Despite of that the recommended threshold values by ROS are reasonable for sure (default values?).

> Actually, I am going through a big refactoring of data structures that hopefully will expose more information to users and allow to some degree of customization. In the meantime, or even as a permanent solution, I had thought of adding some preferences file to HAROS, or something of that sort, where users could fine tune some configurations, as well as passing parameters to plugins.
> 
> Example:

That would be great!

**Comment by git-afsantos** [comment]
A possible workaround, if you need the results quite soon, is to implement a plugin for your own thresholds. Just add a directory and files to your `.haros/plugins` directory. See `mi_calculator` for a full example of a plugin that works on metrics reported by other plugins.

Short example:

```python
MY_THRESHOLD = 20

def process_file_metric(iface, datum):
    metric = datum.metric.id
    if metric != "cyclomatic_complexity":
        return
    if datum.value >= MY_THRESHOLD:
        iface.report_violation("my_cyclomatic_complexity", "CC of " + str(value))
```

And then `plugin.yaml`:

```yaml
name: my_cc_plugin
version: 0.1
rules:
    my_CC_threshold:
        name:           Cyclomatic Complexity Above 20
        scope:          file
        description:    I think CC should not be above 20.
        tags:
            - metrics
            - cyclomatic-complexity
            - custom
```
